refactor: finalize initial generation
vaadin/react-components pull request #14
Opened 2022-10-19 09:03 UTC by Lodin

* Use Vite instead of web-test-runner.
* Use existing web-types.json descriptions instead of web-component-analyzer.
* Add fine-grained entrypoints for components.
* Export all components from root for better picking.
* Add script for generating entrypoint stubs.
* Add script for generating web-types.json schema typings.
* Add script for updating package.json's "exports" section.

2022-10-19 11:14 UTC, platosha requested changes

2022-10-19 11:14 UTC, platosha commented on package.json
> +  "exports": {
I guess having the real files in the `dist` directory could be one advantage, but seems that you’re not going that way...

2022-10-19 11:14 UTC, platosha commented on tsconfig.build.json
> +  "exclude": ["node_modules", "dist"]
Perhaps you want to get rid if the `dist` directory here.

2022-10-19 11:14 UTC, platosha commented on utils/commonjsFix.js
> +// From https://github.com/modernweb-dev/web/issues/1700 -> https://gist.github.com/lucaelin/ffa48cba2253e9ad662b71e38444a135
Is this still used?

2022-10-19 13:31 UTC, Lodin commented on package.json
> +  "exports": {
Added a `dist` folder instead

2022-10-19 15:21 UTC, platosha approved these changes

2022-10-21 08:12 UTC, platosha approved these changes

2022-10-21 08:59 UTC, merged