refactor: split package into core and pro
vaadin/react-components pull request #242
Opened 2024-04-03 09:16 UTC by web-padawan

## Description

Reverts #236 

Re-applies #230

## Type of change

- Refactor

2024-04-03 09:52 UTC, tomivirkki approved these changes

2024-04-03 13:58 UTC, yuriy-fix requested changes
Let's not merge the PR before beta period

2024-05-02 12:04 UTC, mshabarov commented
@yuriy-fix we've just released the 24.4 beta, let's start merging and releasing the restructured React components?

2024-05-03 07:43 UTC, yuriy-fix approved these changes

2024-05-06 06:21 UTC, merged